export const keys = {
	PROPERTIES: 'PROPERTIES',
	FILTERS: 'FILTERS',
	FILTERS2: 'FILTERS2',
	MYBOOKINGS: 'MYBOOKINGS',
	MYBOOKINGSHISTORY: 'MYBOOKINGSHISTORY',
	MYBOOKING: 'MYBOOKING',
	EDITBOOKING: 'EDITBOOKING',
	ADMINBOOKINGS: 'ADMINBOOKINGS',
	UNITDETAILS: 'UNITDETAILS',
	ADVERTISEMENT: 'ADVERTISEMENT',
	ADVERTISEMENTID: 'ADVERTISEMENTID',
	NEARBYPOINTERS: 'NEARBYPOINTERS',
	FAV: 'FAV'
};
