export const keys = {
	PROPERTIES: 'PROPERTIES',
	FILTERS: 'FILTERS',
	MYBOOKINGS: 'MYBOOKINGS',
	MYBOOKINGSHISTORY: 'MYBOOKINGSHISTORY',
	MYBOOKING: 'MYBOOKING',
	EDITBOOKING: 'EDITBOOKING',
	ADMINBOOKINGS: 'ADMINBOOKINGS',
	UNITDETAILS:'UNITDETAILS'

};
