export const keys = {
	properties: 'properties',
	MYBOOKINGS: 'MYBOOKINGS',
	MYBOOKINGSHISTORY: 'MYBOOKINGSHISTORY',
	MYBOOKING: 'MYBOOKING',
	EDITBOOKING: 'EDITBOOKING',
	ADMINBOOKINGS: 'ADMINBOOKINGS',
	UNITDETAILS:'UNITDETAILS'

};
